apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shoot-comparator-pvc
  namespace: kcp-system
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: compare-shoots
  namespace: kcp-system
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      securityContext:
        fsGroup: 65532
      volumes:
      - name: shoot-comparator-pvc
        persistentVolumeClaim:
          claimName: shoot-comparator-pvc
      - name: provisioner-files
        persistentVolumeClaim:
          claimName: test-prov-shoot-read-only
          readOnly: true
      - name: kim-files
        persistentVolumeClaim:
          claimName: test-kim-shoot-read-only
          readOnly: true
      containers:
      - command:
        - /shoot-comparator
        - dirs
        - /testdata/provisioner
        - /testdata/kim
        - --outputDir
        - /results
        image: europe-docker.pkg.dev/kyma-project/dev/shoot-comparator:PR-310
        name: compare-shoots
        resources: {}
        securityContext:
          runAsUser: 65532
        volumeMounts:
        - name: shoot-comparator-pvc
          mountPath: /results
        - name: provisioner-files
          mountPath: /testdata/provisioner
          readOnly: true
        - name: kim-files
          mountPath: /testdata/kim
          readOnly: true
      restartPolicy: Never
