apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mount-prov-volume-with-write-access
  name: mount-prov-volume-with-write-access
  namespace: kcp-system
spec:
  nodeName: "PROVISIONER'S NODE NAME GOES HERE"
  volumes:
    - name: provisioner-ps
      persistentVolumeClaim:
        claimName: test-prov-shoot-spec-storage
  containers:
    - args:
        - /bin/sh
        - -c
        - while true; do date; sleep 3; done
      image: europe-docker.pkg.dev/kyma-project/prod/external/busybox:1.34.1-v1
      name: get-pvc
      volumeMounts:
        - name: provisioner-ps
          mountPath: /testdata/provisioner
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always