module-name: infrastructure-manager
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/infrastructure-manager:v20230914-5174362c
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"
