module-name: infrastructure-manager
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/infrastructure-manager:latest
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"
