apiVersion: infrastructuremanager.kyma-project.io/v1alpha1
kind: Runtime
metadata:
  labels:
    kyma-project.io/instance-id: instance-id
    kyma-project.io/runtime-id: runtime-id
    kyma-project.io/broker-plan-id: plan-id
    kyma-project.io/broker-plan-name: plan-name
    kyma-project.io/global-account-id: global-account-id
    kyma-project.io/subaccount-id: subAccount-id
    kyma-project.io/shoot-name: shoot-name
    kyma-project.io/region: region
    operator.kyma-project.io/kyma-name: kymaName
  name: runtime-id
  namespace: kcp-system
spec:
  shoot:
    # Set by KEB, required
    name: shoot-name
    # Set by KEB, required
    purpose: evaluation
    kubernetes:
      kubeAPIServer:
        ## spec.shoot.kubernetes.kubeAPIServer.oidcConfig is provided by the KEB, required
        oidcConfig:
          clientID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
          groupsClaim: groups
          issuerURL: https://my.cool.tokens.com
          signingAlgs:
            - RS256
          usernameClaim: sub
    provider:
      ## Provided by the KEB, required
      type: aws
      ## Provided by the KEB, required
      region: eu-central-1
      # Provided by the KEB, required.
      # We must consider whether it makes sense to move HAP into KIM
      secretBindingName: "hypersaler secret"
    networking:
      pods: 100.64.0.0/12
      nodes: 10.250.0.0/16
      services: 100.104.0.0/13
    # spec.shoot.controlPlane is provided by the KEB, required
    controlPlane:
      highAvailability:
        failureTolerance:
          type: zone
    workers:
      - machine:
          # Set by KEB, required
          type: m5.xlarge
          # Optional, when not provider default will be used
          # Will be modified by the SRE
          image:
            name: gardenlinux
            version: 1312.3.0
        # Provided by the KEB, required for the first release
        # Finally can be moved into KIM, as it is hardcoded in KEB
        volume:
          type: gp2
          size: 50Gi
        # Provided by the KEB, required
        zones:
          - eu-central-1a
        # Optional, if not provided default will be used
        name: cpu-worker-0
        # Provided by the KEB, required
        minimum: 1
        # Provided by the KEB, required
        maximum: 1
        # Provided by the KEB, required in the first release.
        # It can be optional removed in the future, as it equals to zone count
        maxSurge: 1
        # Provided by the KEB, required in the first release.
        maxUnavailable:  0
  security:
    networking:
      filter:
        # spec.security.networking.filter.egress.enabled is provided by the KEB, required
        egress:
          enabled: false
    # Provided by the KEB, required
    administrators:
      - admin@myorg.com