# permissions for end users to edit clusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: 1errole
    app.kubernetes.io/instance: cluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: infrastructure-manager
    app.kubernetes.io/part-of: infrastructure-manager
    app.kubernetes.io/managed-by: kustomize
  name: cluster-editor-role
  namespace: kcp-system
rules:
- apiGroups:
  - infrastructuremanager.kyma-project.io
  resources:
  - gardenerclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructuremanager.kyma-project.io
  resources:
  - gardenerclusters/status
  verbs:
  - get
