---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infrastructure-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - infrastructuremanager.kyma-project.io
  resources:
  - gardenerclusterprovisioningrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructuremanager.kyma-project.io
  resources:
  - gardenerclusterprovisioningrequests/finalizers
  verbs:
  - update
- apiGroups:
  - infrastructuremanager.kyma-project.io
  resources:
  - gardenerclusterprovisioningrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infrastructuremanager.kyma-project.io
  resources:
  - gardenerclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructuremanager.kyma-project.io
  resources:
  - gardenerclusters/finalizers
  verbs:
  - update
- apiGroups:
  - infrastructuremanager.kyma-project.io
  resources:
  - gardenerclusters/status
  verbs:
  - update
