apiVersion: infrastructuremanager.kyma-project.io/v1
kind: GardenerClusterProvisioningRequest
metadata:
  labels:
    kyma-project.io/instance-id: instance-id
    kyma-project.io/runtime-id: runtime-id
    kyma-project.io/broker-plan-id: plan-id
    kyma-project.io/broker-plan-name: plan-name
    kyma-project.io/global-account-id: global-account-id
    kyma-project.io/subaccount-id: subAccount-id
    kyma-project.io/shoot-name: shoot-name
    kyma-project.io/region: region
    operator.kyma-project.io/kyma-name: kymaName
  name: runtime-id
  namespace: kcp-system
shoot:
  purpose: evaluation
  cloudProfileName: test-profile-name
  kubernetes:
    version: "1.28.7"
    kubeAPIServer:
#        # spec.shoot.kubernetes.kubeAPIServer.oidcConfig was added to meet the following requirement: https://github.com/kyma-project/kyma/issues/18305
#        # the object will be passed by KEB, if not specified defaults will be set
#        # It follows the structure of the shoot spec, and allows creating [OpenIDConnect CR](https://github.com/gardener/gardener-extension-shoot-oidc-service/blob/5fd98637da01deb3f7a99403cd893ee86acd26a8/example/40-openidconnect.yaml#L8)
#        # TODO: when registering new provider KIM also needs to specify permissions for the accounts authenticated by the new provider.
      oidcConfig:
        clientID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        groupsClaim: groups
        issuerURL: https://my.cool.tokens.com
        signingAlgs:
          - RS256
        usernameClaim: sub
        usernamePrefix: '-'
#    # spec.shoot.provider was added to meet the following requirements:
#    # - https://github.com/kyma-project/infrastructure-manager/issues/46
#    # - https://github.com/kyma-project/kyma/issues/18195
#    # It follows the structure of the shoot spec (Provider struct from https://github.com/gardener/gardener/blob/master/pkg/apis/core/types_shoot.go)
#    provider:
#    type: gcp
#      # this field is not obligatory
#      # if not provided the KIM will use HAP to provide secretBindingName
  region: eu-central-1
  seedName: aws-eu5
  secretBindingName: "some secret"
  provider:
    type: gcp
#      controlPlaneConfig:
#        apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
#        kind: ControlPlaneConfig
#        zone: us-central1-b
#      infrastructureConfig:
#        apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
#        kind: InfrastructureConfig
#        networks:
#          worker: 10.250.0.0/22
#          workers: 10.250.0.0/22
    workers:
      - cri:
          name: containerd
        name: worker-klbc9
        machine:
          type: n1-standard-2
          image:
            name: gardenlinux
            version: 1312.3.0
          architecture: amd64
        maximum: 2
        minimum: 1
        maxSurge: 1
        maxUnavailable: 0
        volume:
          type: pd-balanced
          size: 50Gi
        zones:
          - europe-west1-d
#  kubeconfig:
#    secret:
#      name: kubeconfig-runtime-id
#      namespace: kcp-system
#      key: "config"

