apiVersion: infrastructuremanager.kyma-project.io/v1alpha1
kind: Runtime
metadata:
  labels:
    kyma-project.io/instance-id: instance-id
    kyma-project.io/runtime-id: runtime-id
    kyma-project.io/broker-plan-id: plan-id
    kyma-project.io/broker-plan-name: plan-name
    kyma-project.io/global-account-id: global-account-id
    kyma-project.io/subaccount-id: subAccount-id
    kyma-project.io/region: region
    operator.kyma-project.io/kyma-name: kymaName
  name: runtime-id
  namespace: kcp-system
spec:
  shoot:
    # spec.shoot.name is set by the KEB, required
    name: shoot-name
    # spec.shoot.purpose is set by the KEB, required
    purpose: evaluation
    kubernetes:
      kubeAPIServer:
        ## spec.shoot.kubernetes.kubeAPIServer.oidcConfig is provided by the KEB, required
        oidcConfig:
          clientID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
          groupsClaim: groups
          issuerURL: https://my.cool.tokens.com
          signingAlgs:
            - RS256
          usernameClaim: sub
    provider:
      type: aws
      region: eu-central-1
      # We must consider whether it makes sense to move HAP into KIM
      secretBindingName: "hyperscaler secret"
    # spec.shoot.Networking is Provided by the KEB, required
    networking:
      pods: 10.96.0.0/13
      nodes: 10.250.0.0/22
      services: 10.104.0.0/13
    # spec.shoot.controlPlane is provided by the KEB, required
    controlPlane:
      highAvailability:
        failureTolerance:
          type: zone
    workers:
      - machine:
          # spec.shoot.workers.machine.type provided by the KEB, required
          type: mx5.large
        # spec.shoot.workers.zones is provided by the KEB, required
        zones:
          - eu-central-1a
        # spec.shoot.workers.minimum is provided by the KEB, required
        minimum: 1
        # spec.shoot.workers.maximum is provided by the KEB, required
        maximum: 1
        # spec.shoot.workers.maxSurge is provided by the KEB, required in the first release.
        # It can be optional in the future, as it equals to zone count
        maxSurge: 1
        # spec.shoot.workers.maxUnavailable is provided by the KEB, required in the first release.
        # It can be optional in the future, as it is always set to 0
        maxUnavailable:  0
  security:
    networking:
      filter:
        # spec.security.networking.filter.egress.enabled is provided by the KEB, required
        egress:
          enabled: false
    # spec.security.administrators is provided by the KEB, required
    administrators:
      - admin@myorg.com