name: shoot-comparator Build

on:
  push:
    branches:
      - main
    paths:
      - "hack/shoot-comparator/**"
      - "!hack/shoot-comparator/**/*.md"
  pull_request_target:
    types: [opened, synchronize]
    paths:
      - "hack/shoot-comparator/**"
      - "!hack/shoot-comparator/**/*.md"

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  build-image:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: shoot-comparator
      dockerfile: Dockerfile
      context: hack/shoot-comparator
      export-tags: false
