name: utils

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@aaa42aa0628b4ae2578232a66b541047968fac86 #v6.1.0
        with:
          version: v1.61.0
          args: --timeout=10m --skip-files=.*_test\.go --skip-dirs=internal/controller/runtime/fsm/testing
